// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 03.07.2025 17:26:35
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/ercan/OneDrive/Desktop/Starter2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ercan/OneDrive/Desktop/Starter2/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ercan/OneDrive/Desktop/Starter2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ercan/OneDrive/Desktop/Starter2/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ercan/OneDrive/Desktop/Starter2/plugins/**/*.{js,ts,mjs}","C:/Users/ercan/OneDrive/Desktop/Starter2/composables/**/*.{js,ts,mjs}","C:/Users/ercan/OneDrive/Desktop/Starter2/utils/**/*.{js,ts,mjs}","C:/Users/ercan/OneDrive/Desktop/Starter2/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ercan/OneDrive/Desktop/Starter2/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ercan/OneDrive/Desktop/Starter2/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ercan/OneDrive/Desktop/Starter2/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;